### ISSUE TITLE
initial_version和plus_version区别

### ISSUE THREAD

**Issue by JKK-dr** [GoGoGo13579/Planning-and-Control-based-on-Carla-and-ROS2#2]
您好，很棒的工作。想问问您initial_version和plus_version有什么区别呢？我是否能否只使用plus_version从而测试所有的功能呢？

**Comment by GoGoGo13579** [comment]
可以的，plus相当于initial的优化版本，同时会plus会更新更多的算法。我留着initial的原因主要是为了纪念吧，虽然它很不完美，另一个目的是激励大家你看我写的这么差，但是也可以实现一定的功能，你也可以，并且可以做的更好。这是我在B站做的一些成果视频【使用Carla和ros2复现B站up主忠厚老实的老王规控教程—完结】 https://www.bilibili.com/video/BV1bT421e7CM/?share_source=copy_web&vd_source=c6672cbc9ac3f70466950e7ef1e8855a

**Comment by JKK-dr** [comment]
谢谢！很棒的工作
